/* Generated by Yosys 0.41+126 (git sha1 855ac285f, g++ 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module mux_8to1(in, sel, out);
  input [7:0] in;
  wire [7:0] in;
  wire [2:0] in_SB_LUT4_I2_2_O;
  output out;
  wire out;
  wire [3:0] out_SB_LUT4_O_I1;
  input [2:0] sel;
  wire [2:0] sel;
  SB_LUT4 #(
    .LUT_INIT(16'h082a)
  ) in_SB_LUT4_I2 (
    .I0(sel[1]),
    .I1(sel[0]),
    .I2(in[7]),
    .I3(in[6]),
    .O(out_SB_LUT4_O_I1[2])
  );
  SB_LUT4 #(
    .LUT_INIT(16'hf3c0)
  ) in_SB_LUT4_I2_1 (
    .I0(1'h0),
    .I1(sel[0]),
    .I2(in[1]),
    .I3(in[0]),
    .O(in_SB_LUT4_I2_2_O[1])
  );
  SB_LUT4 #(
    .LUT_INIT(16'hf3c0)
  ) in_SB_LUT4_I2_2 (
    .I0(1'h0),
    .I1(sel[0]),
    .I2(in[3]),
    .I3(in[2]),
    .O(in_SB_LUT4_I2_2_O[2])
  );
  SB_LUT4 #(
    .LUT_INIT(16'h0415)
  ) in_SB_LUT4_I2_3 (
    .I0(sel[1]),
    .I1(sel[0]),
    .I2(in[5]),
    .I3(in[4]),
    .O(out_SB_LUT4_O_I1[1])
  );
  SB_LUT4 #(
    .LUT_INIT(16'h5702)
  ) out_SB_LUT4_O (
    .I0(sel[2]),
    .I1(out_SB_LUT4_O_I1[1]),
    .I2(out_SB_LUT4_O_I1[2]),
    .I3(out_SB_LUT4_O_I1[3]),
    .O(out)
  );
  SB_LUT4 #(
    .LUT_INIT(16'hfc30)
  ) sel_SB_LUT4_I1 (
    .I0(1'h0),
    .I1(sel[1]),
    .I2(in_SB_LUT4_I2_2_O[1]),
    .I3(in_SB_LUT4_I2_2_O[2]),
    .O(out_SB_LUT4_O_I1[3])
  );
  assign in_SB_LUT4_I2_2_O[0] = sel[1];
  assign out_SB_LUT4_O_I1[0] = sel[2];
endmodule
