/* Generated by Yosys 0.41+126 (git sha1 855ac285f, g++ 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module FA(A, B, Cin, Sum, Cout);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  wire _5_;
  wire _6_;
  wire _7_;
  input A;
  wire A;
  input B;
  wire B;
  input Cin;
  wire Cin;
  output Cout;
  wire Cout;
  output Sum;
  wire Sum;
  sky130_fd_sc_hd__xor3_1 _8_ (
    .A(_2_),
    .B(_0_),
    .C(_1_),
    .X(_4_)
  );
  sky130_fd_sc_hd__maj3_1 _9_ (
    .A(_2_),
    .B(_0_),
    .C(_1_),
    .X(_3_)
  );
  assign _2_ = Cin;
  assign Sum = _4_;
  assign _0_ = A;
  assign _1_ = B;
  assign Cout = _3_;
endmodule
